# Generated by Django 5.1.7 on 2025-04-07 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_rename_title_post_baslik_rename_body_post_metin_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="yazar",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="metin",
            new_name="body",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="baslik",
            new_name="title",
        ),
    ]
